theme = "catppuccin_mocha"

[editor]
scrolloff = 3
mouse = false
line-number = "relative"
completion-timeout = 100
clipboard-provider = "wayland"

[editor.statusline]
left = ["mode", "spinner"]
center = ["separator","file-name", "separator"]
right = ["diagnostics", "version-control", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "Â¤"
mode.normal = "I AM KEYBOARD GOD"
mode.insert = "FUHUUCK TIME TO WRITE"
mode.select = "THIS IS NOT VIM"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
